language: rust
cache: cargo

matrix:
  include:
    - rust: beta
    - rust: nightly

before_install: set -e

script:
  - bash ci/script.sh

branches:
  only:
    - staging
    - trying

notifications:
  email:
    on_success: never
